version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - 3.0.7
    - 3.1.6
    - 3.1.7
